# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='color',
        ),
    ]
