# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('teal', 'Teal'), ('grey lighten-2', 'Grey'), ('red lighten-1', 'Red')], default='Grey', max_length=50),
        ),
    ]
